version: "3.8"
services:
  elixir-backend:
    build: elixir-backend/docker-image
    container_name: elixir-backend
    networks:
      - the-source-network
    ports:
      - 8090:4000
  php-backend:
    build: php-backend/docker-image
    container_name: php-backend
    networks:
      - the-source-network
    ports:
      - 8080:80
    volumes:
      - ./php-backend/:/var/www/the-rush
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/the-rush/public
  frontend:
    image: nginx
    container_name: frontend
    networks:
      - the-source-network
    volumes:
      - ./frontend/:/usr/share/nginx/html
    ports:
      - 8000:80

networks:
  the-source-network:
    name: the-source-network
    driver: bridge
