name: Elixir CI

on:
  push:
    paths:
      - '**.ex'
      - '**.exs'

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.0.1']
        elixir: ['1.12.0']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: "Install Dependencies"
        working-directory: ./elixir-backend
        run: |
          mix deps.get
      - name: "Run Tests"
        working-directory: ./elixir-backend
        run: |
          mix test
